version: "3"
services:
  pg:
    image: postgres:10.0-alpine
    container_name: executor-postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: crypto-executor
      POSTGRES_USER: executor
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
      
  crypto-executor:
    image: "asinatra/crypto-executor:dev"
    depends_on: 
      - pg
    volumes:
      - /home/crypto/logs:/app/logs
    ports:
      - 5001:5001      
  
volumes:
  pg_data: 